"use client";


interface Step {
  number: string;
  title: string;
  description: string;
  icon: string;
  color: string;
}

const steps: Step[] = [
  {
    number: "1.",
    title: "Configure your directory",
    description: "Clone the repository, customize the website.",
    icon: "⚙️",
    color: "text-blue-400"
  },
  {
    number: "2.",
    title: "Deploy your directory",
    description: "Deploy the project to your preferred platform.",
    icon: "🚀",
    color: "text-purple-400"
  },
  {
    number: "3.",
    title: "Manage the content",
    description: "Manage the content through Supabase dashboard and built-in CMS.",
    icon: "✨",
    color: "text-green-400"
  }
];

const codeContent = `# App Configuration
NEXT_PUBLIC_APP_URL=http://localhost:3000
NODE_ENV=development

# Database (Supabase)
# https://supabase.com/dashboard
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=

# Authentication (NextAuth.js)
NEXTAUTH_SECRET=
NEXTAUTH_URL=http://localhost:3000

# OAuth Providers (Optional)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=

# Email Service (Resend)
# https://resend.com/api-keys
RESEND_API_KEY=

# Payment (Stripe)
# https://dashboard.stripe.com/test/apikeys
STRIPE_PUBLIC_KEY=
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=

# Content Management
DATA_REPOSITORY=
GH_TOKEN=

# Analytics (PostHog)
NEXT_PUBLIC_POSTHOG_KEY=
NEXT_PUBLIC_POSTHOG_HOST=

# Error Tracking (Sentry)
SENTRY_DSN=
SENTRY_ORG=
SENTRY_PROJECT=

# CMS (Sanity)
# https://www.sanity.io/manage
NEXT_PUBLIC_SANITY_PROJECT_ID=
NEXT_PUBLIC_SANITY_DATASET=
SANITY_API_TOKEN=`;

const configContent = `company_name: Ever
content_table: true
item_name: Item
items_name: Items
copyright_year: 2025
generation_method: create-update
max_search_queries: 10
max_results_per_query: 20
max_pages_to_process: 100
relevance_threshold_content: 0.75
min_content_length_for_extraction: 300
ai_first_generation_enabled: true
prompt_comparison_confidence_threshold: 0.5
pr_update:
  branch: feature-1749304574845-oo95yy
  title: Update data - 06/07/2025 13:56
  body: |-
    Update data for awesome-time-tracking
    
    Generated by [Ever Works](https://ever.works)
auth:
  credentials: true         # Email/password login
  google: true              # Google login
  github: true              # GitHub login
  microsoft: true           # Microsoft login
  fb: true                  # Facebook login
  x: true                   # X/Twitter login`;

export function HowItWorks() {
  return (
    <section className="py-20 bg-gray-900 rounded-2xl p-8 border border-gray-800">
        <div>
          {/* Header */}
          <div className="text-center mb-16">
            <p className="text-blue-400 text-sm font-medium tracking-wider uppercase mb-4">
              HOW IT WORKS?
            </p>
            <h2 className="text-4xl md:text-5xl font-bold mb-6">
              Just 3 steps to get started
            </h2>
            <p className="text-gray-400 text-lg max-w-2xl mx-auto">
              Simple setup process to launch your directory website in minutes
            </p>
          </div>

          {/* Content Grid */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">
            {/* Steps */}
            <div className="space-y-8">
              {steps.map((step, index) => (
                <div
                  key={step.number}
                  className={`flex items-start space-x-4 group animate-fade-in`}
                  style={{ animationDelay: `${index * 200}ms` }}
                >
                  {/* Step Line */}
                  <div className="flex flex-col items-center">
                    <div className="w-12 h-12 bg-gray-800 rounded-full flex items-center justify-center group-hover:bg-gray-700 transition-colors">
                      <span className="text-2xl">{step.icon}</span>
                    </div>
                    {index < steps.length - 1 && (
                      <div className="w-px h-16 bg-gray-800 mt-4"></div>
                    )}
                  </div>

                  {/* Content */}
                  <div className="flex-1 pt-2">
                    <h3 className="text-xl font-semibold text-white mb-2 group-hover:text-blue-400 transition-colors">
                      {step.number} {step.title}
                    </h3>
                    <p className="text-gray-400 leading-relaxed">
                      {step.description}
                    </p>
                  </div>
                </div>
              ))}
            </div>

            {/* Code Windows */}
            <div className="space-y-6">
              {/* Environment Variables Window */}
              <div className="animate-fade-in [animation-delay:600ms]">
                <div className="bg-gray-900 rounded-lg border border-gray-800 overflow-hidden shadow-2xl">
                  {/* Window Header */}
                  <div className="bg-gray-800 px-4 py-3 flex items-center justify-between">
                    <div className="flex items-center space-x-2">
                      <div className="w-3 h-3 bg-red-500 rounded-full"></div>
                      <div className="w-3 h-3 bg-yellow-500 rounded-full"></div>
                      <div className="w-3 h-3 bg-green-500 rounded-full"></div>
                    </div>
                    <div className="text-gray-400 text-sm font-mono">.env</div>
                    <div className="w-12"></div>
                  </div>
                  
                  {/* Description */}
                  <div className="bg-gray-800/50 px-4 py-2 border-b border-gray-700">
                    <p className="text-gray-400 text-xs">
                      🔐 <strong>Variables d'environnement</strong> - Configuration technique pour les services externes (API keys, URLs, secrets)
                    </p>
                  </div>

                  {/* Code Content */}
                  <div className="p-4 bg-gray-950 font-mono text-xs h-96 overflow-y-auto">
                    <pre className="text-gray-300 leading-relaxed">
                      <code>
                        {codeContent.split('\n').map((line, index) => (
                          <div key={index} className="flex">
                            <span className="text-gray-600 mr-3 select-none">
                              {String(index + 1).padStart(2, ' ')}
                            </span>
                            <span className={
                              line.startsWith('#') ? 'text-gray-500' :
                              line.includes('=') ? 'text-green-400' :
                              'text-gray-300'
                            }>
                              {line}
                            </span>
                          </div>
                        ))}
                      </code>
                    </pre>
                  </div>
                </div>
              </div>

              {/* Configuration Window */}
              <div className="animate-fade-in [animation-delay:800ms]">
                <div className="bg-gray-900 rounded-lg border border-gray-800 overflow-hidden shadow-2xl">
                  {/* Window Header */}
                  <div className="bg-gray-800 px-4 py-3 flex items-center justify-between">
                    <div className="flex items-center space-x-2">
                      <div className="w-3 h-3 bg-red-500 rounded-full"></div>
                      <div className="w-3 h-3 bg-yellow-500 rounded-full"></div>
                      <div className="w-3 h-3 bg-green-500 rounded-full"></div>
                    </div>
                    <div className="text-gray-400 text-sm font-mono">config.yml</div>
                    <div className="w-12"></div>
                  </div>
                  
                  {/* Description */}
                  <div className="bg-gray-800/50 px-4 py-2 border-b border-gray-700">
                    <p className="text-gray-400 text-xs">
                      🎯 <strong>Configuration Ever Works</strong> - Paramètres métier et comportement de l'application
                    </p>
                  </div>

                  {/* Code Content */}
                  <div className="p-4 bg-gray-950 font-mono text-xs h-96 overflow-y-auto">
                    <pre className="text-gray-300 leading-relaxed">
                      <code>
                        {configContent.split('\n').map((line, index) => (
                          <div key={index} className="flex">
                            <span className="text-gray-600 mr-3 select-none">
                              {String(index + 1).padStart(2, ' ')}
                            </span>
                            <span className={
                              line.trim().startsWith('#') ? 'text-gray-500' :
                              line.includes(':') && !line.trim().startsWith('-') ? 'text-blue-400' :
                              line.trim().startsWith('-') ? 'text-yellow-400' :
                              line.includes('true') || line.includes('false') ? 'text-purple-400' :
                              /^\s*\d+/.test(line) ? 'text-orange-400' :
                              'text-gray-300'
                            }>
                              {line}
                            </span>
                          </div>
                        ))}
                      </code>
                    </pre>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Configuration Explanation */}
          <div className="mt-16 grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* .env Explanation */}
            <div className="bg-gray-900 rounded-lg p-6 border border-gray-800">
              <h3 className="text-lg font-semibold text-white mb-4 flex items-center">
                <span className="text-green-400 mr-2">🔐</span>
                Fenêtre .env (Variables d'environnement)
              </h3>
              <div className="space-y-3 text-sm text-gray-300">
                <div>
                  <strong className="text-blue-400">🔧 App Configuration :</strong>
                  <p>URL de base et environnement de l'application</p>
                </div>
                <div>
                  <strong className="text-blue-400">🗃️ Database (Supabase) :</strong>
                  <p>URL du projet et clés d'accès à la base de données</p>
                </div>
                <div>
                  <strong className="text-blue-400">🔐 Authentication :</strong>
                  <p>Secret NextAuth et URL de callback</p>
                </div>
                <div>
                  <strong className="text-blue-400">👥 OAuth Providers :</strong>
                  <p>Clés pour Google, GitHub, Facebook, etc.</p>
                </div>
                <div>
                  <strong className="text-blue-400">📧 Services externes :</strong>
                  <p>Resend (emails), Stripe (paiements), PostHog (analytics), Sentry (monitoring)</p>
                </div>
              </div>
            </div>

            {/* config.yml Explanation */}
            <div className="bg-gray-900 rounded-lg p-6 border border-gray-800">
              <h3 className="text-lg font-semibold text-white mb-4 flex items-center">
                <span className="text-purple-400 mr-2">🎯</span>
                Fenêtre config.yml (Configuration métier)
              </h3>
              <div className="space-y-3 text-sm text-gray-300">
                <div>
                  <strong className="text-purple-400">🏢 Configuration générale :</strong>
                  <p>Nom de l'entreprise, noms des éléments, copyright</p>
                </div>
                <div>
                  <strong className="text-purple-400">🤖 Paramètres IA :</strong>
                  <p>Génération automatique, limites de recherche, seuils de pertinence</p>
                </div>
                <div>
                  <strong className="text-purple-400">🔄 Mises à jour :</strong>
                  <p>Configuration des Pull Requests automatiques</p>
                </div>
                <div>
                  <strong className="text-purple-400">🔐 Authentification :</strong>
                  <p>Activation des méthodes de connexion (email, réseaux sociaux)</p>
                </div>
                <div>
                  <strong className="text-purple-400">⚙️ Paramètres avancés :</strong>
                  <p>Longueur minimale du contenu, nombre max de pages à traiter</p>
                </div>
              </div>
            </div>
          </div>

          {/* Process Explanation */}
          <div className="mt-12 bg-gradient-to-r from-blue-900/20 to-purple-900/20 rounded-2xl p-8 border border-gray-800">
            <h3 className="text-xl font-bold text-white mb-6 text-center">
              🔄 Processus de configuration
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
              <div className="text-center">
                <div className="w-12 h-12 bg-blue-500 rounded-full flex items-center justify-center mx-auto mb-3">
                  <span className="text-white font-bold">1</span>
                </div>
                <h4 className="font-semibold text-white mb-2">Cloner le repo</h4>
                <p className="text-gray-400 text-sm">Copier .env.example vers .env</p>
              </div>
              <div className="text-center">
                <div className="w-12 h-12 bg-purple-500 rounded-full flex items-center justify-center mx-auto mb-3">
                  <span className="text-white font-bold">2</span>
                </div>
                <h4 className="font-semibold text-white mb-2">Remplir .env</h4>
                <p className="text-gray-400 text-sm">Ajouter vos clés API et secrets</p>
              </div>
              <div className="text-center">
                <div className="w-12 h-12 bg-green-500 rounded-full flex items-center justify-center mx-auto mb-3">
                  <span className="text-white font-bold">3</span>
                </div>
                <h4 className="font-semibold text-white mb-2">Ajuster config.yml</h4>
                <p className="text-gray-400 text-sm">Personnaliser selon vos besoins</p>
              </div>
              <div className="text-center">
                <div className="w-12 h-12 bg-orange-500 rounded-full flex items-center justify-center mx-auto mb-3">
                  <span className="text-white font-bold">4</span>
                </div>
                <h4 className="font-semibold text-white mb-2">Déployer</h4>
                <p className="text-gray-400 text-sm">Lancer votre application</p>
              </div>
            </div>
          </div>

          {/* Advantages */}
          <div className="mt-12 bg-gray-900 rounded-2xl p-8 border border-gray-800">
            <h3 className="text-xl font-bold text-white mb-6 text-center">
              💡 Avantages de cette séparation
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="flex items-start space-x-3">
                <div className="w-8 h-8 bg-green-500 rounded-full flex items-center justify-center flex-shrink-0">
                  <span className="text-white text-sm">🔒</span>
                </div>
                <div>
                  <h4 className="font-semibold text-white mb-1">Sécurité</h4>
                  <p className="text-gray-400 text-sm">Variables sensibles dans .env (non versionnées)</p>
                </div>
              </div>
              <div className="flex items-start space-x-3">
                <div className="w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center flex-shrink-0">
                  <span className="text-white text-sm">⚡</span>
                </div>
                <div>
                  <h4 className="font-semibold text-white mb-1">Flexibilité</h4>
                  <p className="text-gray-400 text-sm">Configuration métier dans config.yml (versionnée)</p>
                </div>
              </div>
              <div className="flex items-start space-x-3">
                <div className="w-8 h-8 bg-purple-500 rounded-full flex items-center justify-center flex-shrink-0">
                  <span className="text-white text-sm">🔧</span>
                </div>
                <div>
                  <h4 className="font-semibold text-white mb-1">Maintenance</h4>
                  <p className="text-gray-400 text-sm">Modification facile sans toucher au code</p>
                </div>
              </div>
              <div className="flex items-start space-x-3">
                <div className="w-8 h-8 bg-orange-500 rounded-full flex items-center justify-center flex-shrink-0">
                  <span className="text-white text-sm">👥</span>
                </div>
                <div>
                  <h4 className="font-semibold text-white mb-1">Équipe</h4>
                  <p className="text-gray-400 text-sm">Développeurs gèrent .env, métier gère config.yml</p>
                </div>
              </div>
            </div>
          </div>

          {/* Bottom CTA */}
          <div className="mt-20 text-center">
            <div className="bg-gradient-to-r from-blue-900/30 to-purple-900/30 rounded-2xl p-8 border border-gray-800">
              <h3 className="text-2xl font-bold mb-4">Ready to Start?</h3>
              <p className="text-gray-400 mb-6">
                Get your directory up and running in less than 10 minutes
              </p>
              <div className="flex flex-wrap justify-center gap-4">
                <div className="flex items-center space-x-2 px-4 py-2 bg-gray-800/50 rounded-lg">
                  <span className="text-green-400">✓</span>
                  <span className="text-sm">One-click deployment</span>
                </div>
                <div className="flex items-center space-x-2 px-4 py-2 bg-gray-800/50 rounded-lg">
                  <span className="text-green-400">✓</span>
                  <span className="text-sm">Supabase Backend</span>
                </div>
                <div className="flex items-center space-x-2 px-4 py-2 bg-gray-800/50 rounded-lg">
                  <span className="text-green-400">✓</span>
                  <span className="text-sm">Environment wizard</span>
                </div>
              </div>
            </div>
          </div>
        </div>
    </section>
  );
} 