"use client";

import { useTranslations } from 'next-intl';
import { ProcessExplanation } from './process-explanation';

interface Step {
  number: string;
  title: string;
  description: string;
  icon: string;
  color: string;
}

const codeContent = `# App Configuration
NEXT_PUBLIC_APP_URL=http://localhost:3000
NODE_ENV=development

# Database (Supabase)
# https://supabase.com/dashboard
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=

# Authentication (NextAuth.js)
NEXTAUTH_SECRET=
NEXTAUTH_URL=http://localhost:3000

# OAuth Providers (Optional)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=

# Email Service (Resend)
# https://resend.com/api-keys
RESEND_API_KEY=

# Payment (Stripe)
# https://dashboard.stripe.com/test/apikeys
STRIPE_PUBLIC_KEY=
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=

# Content Management
DATA_REPOSITORY=
GH_TOKEN=

# Analytics (PostHog)
NEXT_PUBLIC_POSTHOG_KEY=
NEXT_PUBLIC_POSTHOG_HOST=

# Error Tracking (Sentry)
SENTRY_DSN=
SENTRY_ORG=
SENTRY_PROJECT=

# CMS (Sanity)
# https://www.sanity.io/manage
NEXT_PUBLIC_SANITY_PROJECT_ID=
NEXT_PUBLIC_SANITY_DATASET=
SANITY_API_TOKEN=`;

const configContent = `company_name: Ever
content_table: true
item_name: Item
items_name: Items
copyright_year: 2025
generation_method: create-update
max_search_queries: 10
max_results_per_query: 20
max_pages_to_process: 100
relevance_threshold_content: 0.75
min_content_length_for_extraction: 300
ai_first_generation_enabled: true
prompt_comparison_confidence_threshold: 0.5
pr_update:
  branch: feature-1749304574845-oo95yy
  title: Update data - 06/07/2025 13:56
  body: |-
    Update data for awesome-time-tracking
    
    Generated by [Ever Works](https://ever.works)
auth:
  credentials: true         # Email/password login
  google: true              # Google login
  github: true              # GitHub login
  microsoft: true           # Microsoft login
  fb: true                  # Facebook login
  x: true                   # X/Twitter login`;

export function HowItWorks() {
  const t = useTranslations('help');
  
  const steps: Step[] = [
    {
      number: "1.",
      title: t('HOW_IT_WORKS_STEP1_TITLE'),
      description: t('HOW_IT_WORKS_STEP1_DESC'),
      icon: "⚙️",
      color: "text-theme-primary-600 dark:text-theme-primary-400"
    },
    {
      number: "2.",
      title: t('HOW_IT_WORKS_STEP2_TITLE'),
      description: t('HOW_IT_WORKS_STEP2_DESC'),
      icon: "🚀",
      color: "text-theme-secondary-600 dark:text-theme-secondary-400"
    },
    {
      number: "3.",
      title: t('HOW_IT_WORKS_STEP3_TITLE'),
      description: t('HOW_IT_WORKS_STEP3_DESC'),
      icon: "✨",
      color: "text-theme-accent-600 dark:text-theme-accent-400"
    }
  ];

  return (
    <section className="py-20 bg-white/80 dark:bg-gray-800/90 backdrop-blur-sm rounded-2xl p-8 border border-gray-200 dark:border-gray-700 shadow-lg transition-all duration-300">
        <div>
          {/* Header */}
          <div className="text-center mb-16">
            <p className="text-theme-primary-600 dark:text-theme-primary-400 text-sm font-medium tracking-wider uppercase mb-4">
              {t('HOW_IT_WORKS_TITLE')}
            </p>
            <h2 className="text-4xl md:text-5xl font-bold mb-6 text-gray-900 dark:text-white">
              {t('HOW_IT_WORKS_SUBTITLE')}
            </h2>
            <p className="text-gray-600 dark:text-gray-300 text-lg max-w-2xl mx-auto">
              {t('HOW_IT_WORKS_DESCRIPTION')}
            </p>
          </div>

          {/* Content Grid */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">
            {/* Steps */}
            <div className="space-y-8">
              {steps.map((step, index) => (
                <div
                  key={step.number}
                  className={`flex items-start space-x-4 group animate-fade-in`}
                  style={{ animationDelay: `${index * 200}ms` }}
                >
                  {/* Step Line */}
                  <div className="flex flex-col items-center">
                    <div className="w-12 h-12 bg-gray-100 dark:bg-gray-700 rounded-full flex items-center justify-center group-hover:bg-gray-200 dark:group-hover:bg-gray-600 transition-colors border border-gray-200 dark:border-gray-600">
                      <span className="text-2xl">{step.icon}</span>
                    </div>
                    {index < steps.length - 1 && (
                      <div className="w-px h-16 bg-gray-300 dark:bg-gray-600 mt-4"></div>
                    )}
                  </div>

                  {/* Content */}
                  <div className="flex-1 pt-2">
                    <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2 group-hover:text-theme-primary-600 dark:group-hover:text-theme-primary-400 transition-colors">
                      {step.number} {step.title}
                    </h3>
                    <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                      {step.description}
                    </p>
                  </div>
                </div>
              ))}
            </div>

            {/* Code Windows */}
            <div className="space-y-6">
              {/* Environment Variables Window */}
              <div className="animate-fade-in [animation-delay:600ms]">
                <div className="bg-gray-100 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700 overflow-hidden shadow-2xl">
                  {/* Window Header */}
                  <div className="bg-gray-200 dark:bg-gray-800 px-4 py-3 flex items-center justify-between">
                    <div className="flex items-center space-x-2">
                      <div className="w-3 h-3 bg-red-500 rounded-full"></div>
                      <div className="w-3 h-3 bg-yellow-500 rounded-full"></div>
                      <div className="w-3 h-3 bg-green-500 rounded-full"></div>
                    </div>
                    <div className="text-gray-600 dark:text-gray-400 text-sm font-mono">.env</div>
                    <div className="w-12"></div>
                  </div>
                  
                  {/* Description */}
                  <div className="bg-gray-200/50 dark:bg-gray-800/50 px-4 py-2 border-b border-gray-300 dark:border-gray-700">
                    <p className="text-gray-700 dark:text-gray-300 text-xs">
                      🔐 <strong>{t('HOW_IT_WORKS_ENV_TITLE')}</strong> - {t('HOW_IT_WORKS_ENV_DESC')}
                    </p>
                  </div>

                  {/* Code Content */}
                  <div className="p-4 bg-gray-50 dark:bg-gray-950 font-mono text-xs h-96 overflow-y-auto">
                    <pre className="text-gray-800 dark:text-gray-300 leading-relaxed">
                      <code>
                        {codeContent.split('\n').map((line, index) => (
                          <div key={index} className="flex">
                            <span className="text-gray-500 dark:text-gray-600 mr-3 select-none">
                              {String(index + 1).padStart(2, ' ')}
                            </span>
                            <span className={
                              line.startsWith('#') ? 'text-gray-500 dark:text-gray-500' :
                              line.includes('=') ? 'text-theme-secondary-600 dark:text-theme-secondary-400' :
                              'text-gray-800 dark:text-gray-300'
                            }>
                              {line}
                            </span>
                          </div>
                        ))}
                      </code>
                    </pre>
                  </div>
                </div>
              </div>

              {/* Configuration Window */}
              <div className="animate-fade-in [animation-delay:800ms]">
                <div className="bg-gray-100 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700 overflow-hidden shadow-2xl">
                  {/* Window Header */}
                  <div className="bg-gray-200 dark:bg-gray-800 px-4 py-3 flex items-center justify-between">
                    <div className="flex items-center space-x-2">
                      <div className="w-3 h-3 bg-red-500 rounded-full"></div>
                      <div className="w-3 h-3 bg-yellow-500 rounded-full"></div>
                      <div className="w-3 h-3 bg-green-500 rounded-full"></div>
                    </div>
                    <div className="text-gray-600 dark:text-gray-400 text-sm font-mono">config.yml</div>
                    <div className="w-12"></div>
                  </div>
                  
                  {/* Description */}
                  <div className="bg-gray-200/50 dark:bg-gray-800/50 px-4 py-2 border-b border-gray-300 dark:border-gray-700">
                    <p className="text-gray-700 dark:text-gray-300 text-xs">
                      🎯 <strong>{t('HOW_IT_WORKS_CONFIG_TITLE')}</strong> - {t('HOW_IT_WORKS_CONFIG_DESC')}
                    </p>
                  </div>

                  {/* Code Content */}
                  <div className="p-4 bg-gray-50 dark:bg-gray-950 font-mono text-xs h-96 overflow-y-auto">
                    <pre className="text-gray-800 dark:text-gray-300 leading-relaxed">
                      <code>
                        {configContent.split('\n').map((line, index) => (
                          <div key={index} className="flex">
                            <span className="text-gray-500 dark:text-gray-600 mr-3 select-none">
                              {String(index + 1).padStart(2, ' ')}
                            </span>
                            <span className={
                              line.trim().startsWith('#') ? 'text-gray-500 dark:text-gray-500' :
                              line.includes(':') && !line.trim().startsWith('-') ? 'text-theme-primary-600 dark:text-theme-primary-400' :
                              line.trim().startsWith('-') ? 'text-theme-accent-600 dark:text-theme-accent-400' :
                              line.includes('true') || line.includes('false') ? 'text-theme-secondary-600 dark:text-theme-secondary-400' :
                              /^\s*\d+/.test(line) ? 'text-orange-600 dark:text-orange-400' :
                              'text-gray-800 dark:text-gray-300'
                            }>
                              {line}
                            </span>
                          </div>
                        ))}
                      </code>
                    </pre>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Configuration Explanation */}
          <div className="mt-16 grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* .env Explanation */}
            <div className="bg-gray-50 dark:bg-gray-800/70 rounded-lg p-6 border border-gray-200 dark:border-gray-700">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4 flex items-center">
                <span className="text-theme-secondary-600 dark:text-theme-secondary-400 mr-2">🔐</span>
                {t('HOW_IT_WORKS_ENV_WINDOW_TITLE')}
              </h3>
              <div className="space-y-3 text-sm text-gray-700 dark:text-gray-300">
                <div>
                  <strong className="text-theme-primary-600 dark:text-theme-primary-400">🔧 {t('HOW_IT_WORKS_ENV_APP_CONFIG')}</strong>
                  <p>{t('HOW_IT_WORKS_ENV_APP_CONFIG_DESC')}</p>
                </div>
                <div>
                  <strong className="text-theme-primary-600 dark:text-theme-primary-400">🗃️ {t('HOW_IT_WORKS_ENV_DATABASE')}</strong>
                  <p>{t('HOW_IT_WORKS_ENV_DATABASE_DESC')}</p>
                </div>
                <div>
                  <strong className="text-theme-primary-600 dark:text-theme-primary-400">🔐 {t('HOW_IT_WORKS_ENV_AUTH')}</strong>
                  <p>{t('HOW_IT_WORKS_ENV_AUTH_DESC')}</p>
                </div>
                <div>
                  <strong className="text-theme-primary-600 dark:text-theme-primary-400">👥 {t('HOW_IT_WORKS_ENV_OAUTH')}</strong>
                  <p>{t('HOW_IT_WORKS_ENV_OAUTH_DESC')}</p>
                </div>
                <div>
                  <strong className="text-theme-primary-600 dark:text-theme-primary-400">📧 {t('HOW_IT_WORKS_ENV_SERVICES')}</strong>
                  <p>{t('HOW_IT_WORKS_ENV_SERVICES_DESC')}</p>
                </div>
              </div>
            </div>

            {/* config.yml Explanation */}
            <div className="bg-gray-50 dark:bg-gray-800/70 rounded-lg p-6 border border-gray-200 dark:border-gray-700">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4 flex items-center">
                <span className="text-theme-accent-600 dark:text-theme-accent-400 mr-2">🎯</span>
                {t('HOW_IT_WORKS_CONFIG_WINDOW_TITLE')}
              </h3>
              <div className="space-y-3 text-sm text-gray-700 dark:text-gray-300">
                <div>
                  <strong className="text-theme-accent-600 dark:text-theme-accent-400">🏢 {t('HOW_IT_WORKS_CONFIG_GENERAL')}</strong>
                  <p>{t('HOW_IT_WORKS_CONFIG_GENERAL_DESC')}</p>
                </div>
                <div>
                  <strong className="text-theme-accent-600 dark:text-theme-accent-400">🤖 {t('HOW_IT_WORKS_CONFIG_AI')}</strong>
                  <p>{t('HOW_IT_WORKS_CONFIG_AI_DESC')}</p>
                </div>
                <div>
                  <strong className="text-theme-accent-600 dark:text-theme-accent-400">🔄 {t('HOW_IT_WORKS_CONFIG_UPDATES')}</strong>
                  <p>{t('HOW_IT_WORKS_CONFIG_UPDATES_DESC')}</p>
                </div>
                <div>
                  <strong className="text-theme-accent-600 dark:text-theme-accent-400">🔐 {t('HOW_IT_WORKS_CONFIG_AUTHENTICATION')}</strong>
                  <p>{t('HOW_IT_WORKS_CONFIG_AUTHENTICATION_DESC')}</p>
                </div>
                <div>
                  <strong className="text-theme-accent-600 dark:text-theme-accent-400">⚙️ {t('HOW_IT_WORKS_CONFIG_ADVANCED')}</strong>
                  <p>{t('HOW_IT_WORKS_CONFIG_ADVANCED_DESC')}</p>
                </div>
              </div>
            </div>
          </div>

      <ProcessExplanation />

          {/* Advantages */}
          <div className="mt-12 bg-gray-50 dark:bg-gray-800/70 rounded-2xl p-8 border border-gray-200 dark:border-gray-700">
            <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-6 text-center">
              💡 {t('HOW_IT_WORKS_ADVANTAGES_TITLE')}
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="flex items-start space-x-3">
                <div className="w-8 h-8 bg-theme-secondary-500 dark:bg-theme-secondary-400 rounded-full flex items-center justify-center flex-shrink-0">
                  <span className="text-white text-sm">🔒</span>
                </div>
                <div>
                  <h4 className="font-semibold text-gray-900 dark:text-white mb-1">{t('HOW_IT_WORKS_ADVANTAGES_SECURITY')}</h4>
                  <p className="text-gray-600 dark:text-gray-400 text-sm">{t('HOW_IT_WORKS_ADVANTAGES_SECURITY_DESC')}</p>
                </div>
              </div>
              <div className="flex items-start space-x-3">
                <div className="w-8 h-8 bg-theme-primary-500 dark:bg-theme-primary-400 rounded-full flex items-center justify-center flex-shrink-0">
                  <span className="text-white text-sm">⚡</span>
                </div>
                <div>
                  <h4 className="font-semibold text-gray-900 dark:text-white mb-1">{t('HOW_IT_WORKS_ADVANTAGES_FLEXIBILITY')}</h4>
                  <p className="text-gray-600 dark:text-gray-400 text-sm">{t('HOW_IT_WORKS_ADVANTAGES_FLEXIBILITY_DESC')}</p>
                </div>
              </div>
              <div className="flex items-start space-x-3">
                <div className="w-8 h-8 bg-theme-accent-500 dark:bg-theme-accent-400 rounded-full flex items-center justify-center flex-shrink-0">
                  <span className="text-white text-sm">🔧</span>
                </div>
                <div>
                  <h4 className="font-semibold text-gray-900 dark:text-white mb-1">{t('HOW_IT_WORKS_ADVANTAGES_MAINTENANCE')}</h4>
                  <p className="text-gray-600 dark:text-gray-400 text-sm">{t('HOW_IT_WORKS_ADVANTAGES_MAINTENANCE_DESC')}</p>
                </div>
              </div>
              <div className="flex items-start space-x-3">
                <div className="w-8 h-8 bg-orange-500 dark:bg-orange-400 rounded-full flex items-center justify-center flex-shrink-0">
                  <span className="text-white text-sm">👥</span>
                </div>
                <div>
                  <h4 className="font-semibold text-gray-900 dark:text-white mb-1">{t('HOW_IT_WORKS_ADVANTAGES_TEAM')}</h4>
                  <p className="text-gray-600 dark:text-gray-400 text-sm">{t('HOW_IT_WORKS_ADVANTAGES_TEAM_DESC')}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Bottom CTA */}
          <div className="mt-20 text-center">
            <div className="bg-gradient-to-r from-theme-primary-100 to-theme-secondary-100 dark:from-theme-primary-900/30 dark:to-theme-secondary-900/30 rounded-2xl p-8 border border-gray-200 dark:border-gray-700">
              <h3 className="text-2xl font-bold mb-4 text-gray-900 dark:text-white">{t('HOW_IT_WORKS_CTA_TITLE')}</h3>
              <p className="text-gray-600 dark:text-gray-400 mb-6">
                {t('HOW_IT_WORKS_CTA_DESC')}
              </p>
              <div className="flex flex-wrap justify-center gap-4">
                <div className="flex items-center space-x-2 px-4 py-2 bg-white/80 dark:bg-gray-800/50 rounded-lg border border-gray-200 dark:border-gray-600">
                  <span className="text-theme-secondary-600 dark:text-theme-secondary-400">✓</span>
                  <span className="text-sm text-gray-700 dark:text-gray-300">{t('HOW_IT_WORKS_CTA_DEPLOY')}</span>
                </div>
                <div className="flex items-center space-x-2 px-4 py-2 bg-white/80 dark:bg-gray-800/50 rounded-lg border border-gray-200 dark:border-gray-600">
                  <span className="text-theme-secondary-600 dark:text-theme-secondary-400">✓</span>
                  <span className="text-sm text-gray-700 dark:text-gray-300">{t('HOW_IT_WORKS_CTA_BACKEND')}</span>
                </div>
                <div className="flex items-center space-x-2 px-4 py-2 bg-white/80 dark:bg-gray-800/50 rounded-lg border border-gray-200 dark:border-gray-600">
                  <span className="text-theme-secondary-600 dark:text-theme-secondary-400">✓</span>
                  <span className="text-sm text-gray-700 dark:text-gray-300">{t('HOW_IT_WORKS_CTA_WIZARD')}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
    </section>
  );
} 